#!/bin/bash
#
# Author: Kjartan B. Kristjansson
#
# A script that outputs the status and charge of the laptop battery.
# It will proably not work on other machines unless they have the
# same battery configuration.
# Intended for use with i3blocks.

# Directory of battery data files.
batt_dir='/sys/class/power_supply/BAT1'

stat=$(cat $batt_dir/status)
charge_now=$(cat $batt_dir/charge_now)
charge_full=$(cat $batt_dir/charge_full)
charge=$(cat $batt_dir/capacity)

if [ "$stat" == "Discharging" ]; then
    # Second string is empty so the color property will be in the correct place.
    echo "BAT $charge %"
    echo
    if [ "$charge" -ge 70 ]; then
        echo \#00FF00
    elif [ "$charge" -ge 40 ]; then 
        echo \#FFFF00
    elif [ "$charge" -ge 20 ]; then 
        echo \#FF6600
    else
        echo \#FF0000
        exit 33
    fi
elif [ "$stat" == "Full" ]; then
    echo ""
    echo
    echo \#00FF00
else
    echo "CHR $charge %"
    echo
    echo \#00FF00
fi

exit 0
